//! Pixzig's own input identity enums, and the mapping from SDL3's native
//! codes onto them.
//!
//! These enums are the engine's public vocabulary for keys, mouse buttons
//! and gamepad controls. They deliberately do not expose the backend's
//! values: nothing outside this file mentions `SDL_Scancode`, `SDL_Keycode`
//! or `SDL_GamepadButton`; games, Lua bindings and Python bindings use the
//! pixzig names and values.
//!
//! The values are dense (0..N-1, `unknown` first for `Key`), which is what
//! lets `Keyboard`/`Mouse`/`Gamepad` index their bitsets with a plain
//! `@intFromEnum`. `tools/gen_py_constants.zig` regenerates
//! `python/pixzig/constants.py` from these declarations, so the Python side
//! can never drift from them.

const std = @import("std");
const sdl = @import("sdl3");

/// A key's *physical position* on the keyboard, from SDL's scancode.
///
/// Position, not keycap: `.w` is the key where W sits on a US QWERTY board
/// no matter which layout is active, so WASD movement stays under the same
/// fingers on AZERTY or Dvorak. That is what a game wants from key
/// bindings. It is emphatically *not* what text entry wants -- use
/// `Keyboard.text()` for that, which is UTF-8 already resolved through the
/// active layout, dead keys and IME. For UI that cares about the keycap
/// (a "press Y to confirm" prompt on a non-QWERTY layout, say), the
/// layout-resolved identity of the same key is available from
/// `Keyboard.layoutDown()` and friends.
///
/// Field names are stable API for games, `ActionMap` binding strings and
/// saved keybind configs.
pub const Key = enum {
    unknown,
    space,
    apostrophe,
    comma,
    minus,
    period,
    slash,
    zero,
    one,
    two,
    three,
    four,
    five,
    six,
    seven,
    eight,
    nine,
    semicolon,
    equal,
    a,
    b,
    c,
    d,
    e,
    f,
    g,
    h,
    i,
    j,
    k,
    l,
    m,
    n,
    o,
    p,
    q,
    r,
    s,
    t,
    u,
    v,
    w,
    x,
    y,
    z,
    left_bracket,
    backslash,
    right_bracket,
    grave_accent,
    escape,
    enter,
    tab,
    backspace,
    insert,
    delete,
    right,
    left,
    down,
    up,
    page_up,
    page_down,
    home,
    end,
    caps_lock,
    scroll_lock,
    num_lock,
    print_screen,
    pause,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    kp_0,
    kp_1,
    kp_2,
    kp_3,
    kp_4,
    kp_5,
    kp_6,
    kp_7,
    kp_8,
    kp_9,
    kp_decimal,
    kp_divide,
    kp_multiply,
    kp_subtract,
    kp_add,
    kp_enter,
    kp_equal,
    left_shift,
    left_control,
    left_alt,
    left_super,
    right_shift,
    right_control,
    right_alt,
    right_super,
    menu,
};

/// Mouse buttons. `x1`/`x2` are the side buttons.
pub const MouseButton = enum {
    left,
    right,
    middle,
    x1,
    x2,
};

/// Gamepad face/shoulder/dpad buttons, in standard-layout names.
/// `a`/`b`/`x`/`y` are positional (SDL3 calls them south/east/west/north),
/// so on a Nintendo-style pad `.a` is still the bottom face button.
pub const GamepadButton = enum {
    a,
    b,
    x,
    y,
    left_bumper,
    right_bumper,
    back,
    start,
    guide,
    left_thumb,
    right_thumb,
    dpad_up,
    dpad_right,
    dpad_down,
    dpad_left,
};

/// Gamepad analog axes. Sticks report -1..1; triggers report 0..32767 from
/// SDL and are rescaled to the engine's -1..1 range.
pub const GamepadAxis = enum {
    left_x,
    left_y,
    right_x,
    right_y,
    left_trigger,
    right_trigger,
};

pub const NumKeys = @typeInfo(Key).@"enum".fields.len;
pub const NumMouseButtons = @typeInfo(MouseButton).@"enum".fields.len;
pub const NumGamepadButtons = @typeInfo(GamepadButton).@"enum".fields.len;
pub const NumGamepadAxes = @typeInfo(GamepadAxis).@"enum".fields.len;

/// Dense bitset index for a key.
pub fn keyIndex(key: Key) usize {
    return @intFromEnum(key);
}

pub fn mouseButtonIndex(btn: MouseButton) usize {
    return @intFromEnum(btn);
}

/// Maps an SDL scancode (physical position) to a `Key`.
pub fn fromScancode(sc: sdl.SDL_Scancode) Key {
    return switch (sc) {
        sdl.SDL_SCANCODE_SPACE => .space,
        sdl.SDL_SCANCODE_APOSTROPHE => .apostrophe,
        sdl.SDL_SCANCODE_COMMA => .comma,
        sdl.SDL_SCANCODE_MINUS => .minus,
        sdl.SDL_SCANCODE_PERIOD => .period,
        sdl.SDL_SCANCODE_SLASH => .slash,
        sdl.SDL_SCANCODE_0 => .zero,
        sdl.SDL_SCANCODE_1 => .one,
        sdl.SDL_SCANCODE_2 => .two,
        sdl.SDL_SCANCODE_3 => .three,
        sdl.SDL_SCANCODE_4 => .four,
        sdl.SDL_SCANCODE_5 => .five,
        sdl.SDL_SCANCODE_6 => .six,
        sdl.SDL_SCANCODE_7 => .seven,
        sdl.SDL_SCANCODE_8 => .eight,
        sdl.SDL_SCANCODE_9 => .nine,
        sdl.SDL_SCANCODE_SEMICOLON => .semicolon,
        sdl.SDL_SCANCODE_EQUALS => .equal,
        sdl.SDL_SCANCODE_A => .a,
        sdl.SDL_SCANCODE_B => .b,
        sdl.SDL_SCANCODE_C => .c,
        sdl.SDL_SCANCODE_D => .d,
        sdl.SDL_SCANCODE_E => .e,
        sdl.SDL_SCANCODE_F => .f,
        sdl.SDL_SCANCODE_G => .g,
        sdl.SDL_SCANCODE_H => .h,
        sdl.SDL_SCANCODE_I => .i,
        sdl.SDL_SCANCODE_J => .j,
        sdl.SDL_SCANCODE_K => .k,
        sdl.SDL_SCANCODE_L => .l,
        sdl.SDL_SCANCODE_M => .m,
        sdl.SDL_SCANCODE_N => .n,
        sdl.SDL_SCANCODE_O => .o,
        sdl.SDL_SCANCODE_P => .p,
        sdl.SDL_SCANCODE_Q => .q,
        sdl.SDL_SCANCODE_R => .r,
        sdl.SDL_SCANCODE_S => .s,
        sdl.SDL_SCANCODE_T => .t,
        sdl.SDL_SCANCODE_U => .u,
        sdl.SDL_SCANCODE_V => .v,
        sdl.SDL_SCANCODE_W => .w,
        sdl.SDL_SCANCODE_X => .x,
        sdl.SDL_SCANCODE_Y => .y,
        sdl.SDL_SCANCODE_Z => .z,
        sdl.SDL_SCANCODE_LEFTBRACKET => .left_bracket,
        sdl.SDL_SCANCODE_BACKSLASH => .backslash,
        sdl.SDL_SCANCODE_RIGHTBRACKET => .right_bracket,
        sdl.SDL_SCANCODE_GRAVE => .grave_accent,
        sdl.SDL_SCANCODE_ESCAPE => .escape,
        sdl.SDL_SCANCODE_RETURN => .enter,
        sdl.SDL_SCANCODE_TAB => .tab,
        sdl.SDL_SCANCODE_BACKSPACE => .backspace,
        sdl.SDL_SCANCODE_INSERT => .insert,
        sdl.SDL_SCANCODE_DELETE => .delete,
        sdl.SDL_SCANCODE_RIGHT => .right,
        sdl.SDL_SCANCODE_LEFT => .left,
        sdl.SDL_SCANCODE_DOWN => .down,
        sdl.SDL_SCANCODE_UP => .up,
        sdl.SDL_SCANCODE_PAGEUP => .page_up,
        sdl.SDL_SCANCODE_PAGEDOWN => .page_down,
        sdl.SDL_SCANCODE_HOME => .home,
        sdl.SDL_SCANCODE_END => .end,
        sdl.SDL_SCANCODE_CAPSLOCK => .caps_lock,
        sdl.SDL_SCANCODE_SCROLLLOCK => .scroll_lock,
        sdl.SDL_SCANCODE_NUMLOCKCLEAR => .num_lock,
        sdl.SDL_SCANCODE_PRINTSCREEN => .print_screen,
        sdl.SDL_SCANCODE_PAUSE => .pause,
        sdl.SDL_SCANCODE_F1 => .F1,
        sdl.SDL_SCANCODE_F2 => .F2,
        sdl.SDL_SCANCODE_F3 => .F3,
        sdl.SDL_SCANCODE_F4 => .F4,
        sdl.SDL_SCANCODE_F5 => .F5,
        sdl.SDL_SCANCODE_F6 => .F6,
        sdl.SDL_SCANCODE_F7 => .F7,
        sdl.SDL_SCANCODE_F8 => .F8,
        sdl.SDL_SCANCODE_F9 => .F9,
        sdl.SDL_SCANCODE_F10 => .F10,
        sdl.SDL_SCANCODE_F11 => .F11,
        sdl.SDL_SCANCODE_F12 => .F12,
        sdl.SDL_SCANCODE_F13 => .F13,
        sdl.SDL_SCANCODE_F14 => .F14,
        sdl.SDL_SCANCODE_F15 => .F15,
        sdl.SDL_SCANCODE_F16 => .F16,
        sdl.SDL_SCANCODE_F17 => .F17,
        sdl.SDL_SCANCODE_F18 => .F18,
        sdl.SDL_SCANCODE_F19 => .F19,
        sdl.SDL_SCANCODE_F20 => .F20,
        sdl.SDL_SCANCODE_F21 => .F21,
        sdl.SDL_SCANCODE_F22 => .F22,
        sdl.SDL_SCANCODE_F23 => .F23,
        sdl.SDL_SCANCODE_F24 => .F24,
        sdl.SDL_SCANCODE_KP_0 => .kp_0,
        sdl.SDL_SCANCODE_KP_1 => .kp_1,
        sdl.SDL_SCANCODE_KP_2 => .kp_2,
        sdl.SDL_SCANCODE_KP_3 => .kp_3,
        sdl.SDL_SCANCODE_KP_4 => .kp_4,
        sdl.SDL_SCANCODE_KP_5 => .kp_5,
        sdl.SDL_SCANCODE_KP_6 => .kp_6,
        sdl.SDL_SCANCODE_KP_7 => .kp_7,
        sdl.SDL_SCANCODE_KP_8 => .kp_8,
        sdl.SDL_SCANCODE_KP_9 => .kp_9,
        sdl.SDL_SCANCODE_KP_PERIOD => .kp_decimal,
        sdl.SDL_SCANCODE_KP_DIVIDE => .kp_divide,
        sdl.SDL_SCANCODE_KP_MULTIPLY => .kp_multiply,
        sdl.SDL_SCANCODE_KP_MINUS => .kp_subtract,
        sdl.SDL_SCANCODE_KP_PLUS => .kp_add,
        sdl.SDL_SCANCODE_KP_ENTER => .kp_enter,
        sdl.SDL_SCANCODE_KP_EQUALS => .kp_equal,
        sdl.SDL_SCANCODE_LSHIFT => .left_shift,
        sdl.SDL_SCANCODE_LCTRL => .left_control,
        sdl.SDL_SCANCODE_LALT => .left_alt,
        sdl.SDL_SCANCODE_LGUI => .left_super,
        sdl.SDL_SCANCODE_RSHIFT => .right_shift,
        sdl.SDL_SCANCODE_RCTRL => .right_control,
        sdl.SDL_SCANCODE_RALT => .right_alt,
        sdl.SDL_SCANCODE_RGUI => .right_super,
        sdl.SDL_SCANCODE_APPLICATION => .menu,
        else => .unknown,
    };
}

/// Maps an SDL keycode (the identity on the keycap under the active OS
/// layout) to a `Key`. Feeds `Keyboard`'s secondary "layout" bitset.
pub fn fromKeycode(kc: sdl.SDL_Keycode) Key {
    return switch (kc) {
        sdl.SDLK_SPACE => .space,
        sdl.SDLK_APOSTROPHE => .apostrophe,
        sdl.SDLK_COMMA => .comma,
        sdl.SDLK_MINUS => .minus,
        sdl.SDLK_PERIOD => .period,
        sdl.SDLK_SLASH => .slash,
        sdl.SDLK_0 => .zero,
        sdl.SDLK_1 => .one,
        sdl.SDLK_2 => .two,
        sdl.SDLK_3 => .three,
        sdl.SDLK_4 => .four,
        sdl.SDLK_5 => .five,
        sdl.SDLK_6 => .six,
        sdl.SDLK_7 => .seven,
        sdl.SDLK_8 => .eight,
        sdl.SDLK_9 => .nine,
        sdl.SDLK_SEMICOLON => .semicolon,
        sdl.SDLK_EQUALS => .equal,
        sdl.SDLK_A => .a,
        sdl.SDLK_B => .b,
        sdl.SDLK_C => .c,
        sdl.SDLK_D => .d,
        sdl.SDLK_E => .e,
        sdl.SDLK_F => .f,
        sdl.SDLK_G => .g,
        sdl.SDLK_H => .h,
        sdl.SDLK_I => .i,
        sdl.SDLK_J => .j,
        sdl.SDLK_K => .k,
        sdl.SDLK_L => .l,
        sdl.SDLK_M => .m,
        sdl.SDLK_N => .n,
        sdl.SDLK_O => .o,
        sdl.SDLK_P => .p,
        sdl.SDLK_Q => .q,
        sdl.SDLK_R => .r,
        sdl.SDLK_S => .s,
        sdl.SDLK_T => .t,
        sdl.SDLK_U => .u,
        sdl.SDLK_V => .v,
        sdl.SDLK_W => .w,
        sdl.SDLK_X => .x,
        sdl.SDLK_Y => .y,
        sdl.SDLK_Z => .z,
        sdl.SDLK_LEFTBRACKET => .left_bracket,
        sdl.SDLK_BACKSLASH => .backslash,
        sdl.SDLK_RIGHTBRACKET => .right_bracket,
        sdl.SDLK_GRAVE => .grave_accent,
        sdl.SDLK_ESCAPE => .escape,
        sdl.SDLK_RETURN => .enter,
        sdl.SDLK_TAB => .tab,
        sdl.SDLK_BACKSPACE => .backspace,
        sdl.SDLK_INSERT => .insert,
        sdl.SDLK_DELETE => .delete,
        sdl.SDLK_RIGHT => .right,
        sdl.SDLK_LEFT => .left,
        sdl.SDLK_DOWN => .down,
        sdl.SDLK_UP => .up,
        sdl.SDLK_PAGEUP => .page_up,
        sdl.SDLK_PAGEDOWN => .page_down,
        sdl.SDLK_HOME => .home,
        sdl.SDLK_END => .end,
        sdl.SDLK_CAPSLOCK => .caps_lock,
        sdl.SDLK_SCROLLLOCK => .scroll_lock,
        sdl.SDLK_NUMLOCKCLEAR => .num_lock,
        sdl.SDLK_PRINTSCREEN => .print_screen,
        sdl.SDLK_PAUSE => .pause,
        sdl.SDLK_F1 => .F1,
        sdl.SDLK_F2 => .F2,
        sdl.SDLK_F3 => .F3,
        sdl.SDLK_F4 => .F4,
        sdl.SDLK_F5 => .F5,
        sdl.SDLK_F6 => .F6,
        sdl.SDLK_F7 => .F7,
        sdl.SDLK_F8 => .F8,
        sdl.SDLK_F9 => .F9,
        sdl.SDLK_F10 => .F10,
        sdl.SDLK_F11 => .F11,
        sdl.SDLK_F12 => .F12,
        sdl.SDLK_F13 => .F13,
        sdl.SDLK_F14 => .F14,
        sdl.SDLK_F15 => .F15,
        sdl.SDLK_F16 => .F16,
        sdl.SDLK_F17 => .F17,
        sdl.SDLK_F18 => .F18,
        sdl.SDLK_F19 => .F19,
        sdl.SDLK_F20 => .F20,
        sdl.SDLK_F21 => .F21,
        sdl.SDLK_F22 => .F22,
        sdl.SDLK_F23 => .F23,
        sdl.SDLK_F24 => .F24,
        sdl.SDLK_KP_0 => .kp_0,
        sdl.SDLK_KP_1 => .kp_1,
        sdl.SDLK_KP_2 => .kp_2,
        sdl.SDLK_KP_3 => .kp_3,
        sdl.SDLK_KP_4 => .kp_4,
        sdl.SDLK_KP_5 => .kp_5,
        sdl.SDLK_KP_6 => .kp_6,
        sdl.SDLK_KP_7 => .kp_7,
        sdl.SDLK_KP_8 => .kp_8,
        sdl.SDLK_KP_9 => .kp_9,
        sdl.SDLK_KP_PERIOD => .kp_decimal,
        sdl.SDLK_KP_DIVIDE => .kp_divide,
        sdl.SDLK_KP_MULTIPLY => .kp_multiply,
        sdl.SDLK_KP_MINUS => .kp_subtract,
        sdl.SDLK_KP_PLUS => .kp_add,
        sdl.SDLK_KP_ENTER => .kp_enter,
        sdl.SDLK_KP_EQUALS => .kp_equal,
        sdl.SDLK_LSHIFT => .left_shift,
        sdl.SDLK_LCTRL => .left_control,
        sdl.SDLK_LALT => .left_alt,
        sdl.SDLK_LGUI => .left_super,
        sdl.SDLK_RSHIFT => .right_shift,
        sdl.SDLK_RCTRL => .right_control,
        sdl.SDLK_RALT => .right_alt,
        sdl.SDLK_RGUI => .right_super,
        sdl.SDLK_APPLICATION => .menu,
        else => .unknown,
    };
}

/// Maps SDL's 1-based mouse button number. Returns null for buttons past
/// `x2`, which this engine does not model.
pub fn fromSdlMouseButton(button: u8) ?MouseButton {
    return switch (button) {
        sdl.SDL_BUTTON_LEFT => .left,
        sdl.SDL_BUTTON_RIGHT => .right,
        sdl.SDL_BUTTON_MIDDLE => .middle,
        sdl.SDL_BUTTON_X1 => .x1,
        sdl.SDL_BUTTON_X2 => .x2,
        else => null,
    };
}

/// The SDL button id for one of ours, used by `Gamepad`'s polling path.
pub fn toSdlGamepadButton(button: GamepadButton) sdl.SDL_GamepadButton {
    return switch (button) {
        .a => sdl.SDL_GAMEPAD_BUTTON_SOUTH,
        .b => sdl.SDL_GAMEPAD_BUTTON_EAST,
        .x => sdl.SDL_GAMEPAD_BUTTON_WEST,
        .y => sdl.SDL_GAMEPAD_BUTTON_NORTH,
        .left_bumper => sdl.SDL_GAMEPAD_BUTTON_LEFT_SHOULDER,
        .right_bumper => sdl.SDL_GAMEPAD_BUTTON_RIGHT_SHOULDER,
        .back => sdl.SDL_GAMEPAD_BUTTON_BACK,
        .start => sdl.SDL_GAMEPAD_BUTTON_START,
        .guide => sdl.SDL_GAMEPAD_BUTTON_GUIDE,
        .left_thumb => sdl.SDL_GAMEPAD_BUTTON_LEFT_STICK,
        .right_thumb => sdl.SDL_GAMEPAD_BUTTON_RIGHT_STICK,
        .dpad_up => sdl.SDL_GAMEPAD_BUTTON_DPAD_UP,
        .dpad_right => sdl.SDL_GAMEPAD_BUTTON_DPAD_RIGHT,
        .dpad_down => sdl.SDL_GAMEPAD_BUTTON_DPAD_DOWN,
        .dpad_left => sdl.SDL_GAMEPAD_BUTTON_DPAD_LEFT,
    };
}

/// The SDL axis id for one of ours, used by `Gamepad`'s polling path.
pub fn toSdlGamepadAxis(axis: GamepadAxis) sdl.SDL_GamepadAxis {
    return switch (axis) {
        .left_x => sdl.SDL_GAMEPAD_AXIS_LEFTX,
        .left_y => sdl.SDL_GAMEPAD_AXIS_LEFTY,
        .right_x => sdl.SDL_GAMEPAD_AXIS_RIGHTX,
        .right_y => sdl.SDL_GAMEPAD_AXIS_RIGHTY,
        .left_trigger => sdl.SDL_GAMEPAD_AXIS_LEFT_TRIGGER,
        .right_trigger => sdl.SDL_GAMEPAD_AXIS_RIGHT_TRIGGER,
    };
}

/// Converts SDL's raw i16 axis reading to a float. Sticks map onto -1..1;
/// triggers, which SDL reports as 0..32767, are rescaled onto the engine's
/// -1..1 range.
pub fn axisValue(axis: GamepadAxis, raw: i16) f32 {
    const v = @as(f32, @floatFromInt(raw)) / 32767.0;
    return switch (axis) {
        .left_trigger, .right_trigger => std.math.clamp(v * 2.0 - 1.0, -1.0, 1.0),
        else => std.math.clamp(v, -1.0, 1.0),
    };
}

/// A human-readable name for a key, for printing key chords in menus and
/// help text. Punctuation keys print as the symbol on the keycap and
/// letters print uppercase; anything without a nicer spelling falls back to
/// the enum field name.
pub fn displayName(key: Key) []const u8 {
    return switch (key) {
        .space => "space",
        .apostrophe => "'",
        .comma => ",",
        .minus => "-",
        .period => ".",
        .slash => "/",
        .zero => "0",
        .one => "1",
        .two => "2",
        .three => "3",
        .four => "4",
        .five => "5",
        .six => "6",
        .seven => "7",
        .eight => "8",
        .nine => "9",
        .semicolon => ";",
        .equal => "=",
        .a => "A",
        .b => "B",
        .c => "C",
        .d => "D",
        .e => "E",
        .f => "F",
        .g => "G",
        .h => "H",
        .i => "I",
        .j => "J",
        .k => "K",
        .l => "L",
        .m => "M",
        .n => "N",
        .o => "O",
        .p => "P",
        .q => "Q",
        .r => "R",
        .s => "S",
        .t => "T",
        .u => "U",
        .v => "V",
        .w => "W",
        .x => "X",
        .y => "Y",
        .z => "Z",
        .left_bracket => "[",
        .backslash => "\\",
        .right_bracket => "]",
        .grave_accent => "`",
        .F1 => "F1",
        .F2 => "F2",
        .F3 => "F3",
        .F4 => "F4",
        .F5 => "F5",
        .F6 => "F6",
        .F7 => "F7",
        .F8 => "F8",
        .F9 => "F9",
        .F10 => "F10",
        .F11 => "F11",
        .F12 => "F12",
        .F13 => "F13",
        .F14 => "F14",
        .F15 => "F15",
        .F16 => "F16",
        .F17 => "F17",
        .F18 => "F18",
        .F19 => "F19",
        .F20 => "F20",
        .F21 => "F21",
        .F22 => "F22",
        .F23 => "F23",
        .F24 => "F24",
        else => @tagName(key),
    };
}

/// The ASCII character a key produces, or null when it produces none.
///
/// This is a US-QWERTY approximation kept for the console and other
/// keyboard-driven text widgets that predate `Keyboard.text()`. It is
/// wrong for any other layout by construction, since `Key` is a physical
/// position. New code that wants typed characters should read
/// `Keyboard.text()`, which is layout-, dead-key- and IME-correct.
pub fn charFromKey(key: Key, shift: bool) ?u8 {
    if (shift) {
        return switch (key) {
            .a => 'A',
            .b => 'B',
            .c => 'C',
            .d => 'D',
            .e => 'E',
            .f => 'F',
            .g => 'G',
            .h => 'H',
            .i => 'I',
            .j => 'J',
            .k => 'K',
            .l => 'L',
            .m => 'M',
            .n => 'N',
            .o => 'O',
            .p => 'P',
            .q => 'Q',
            .r => 'R',
            .s => 'S',
            .t => 'T',
            .u => 'U',
            .v => 'V',
            .w => 'W',
            .x => 'X',
            .y => 'Y',
            .z => 'Z',
            .one => '!',
            .two => '@',
            .three => '#',
            .four => '$',
            .five => '%',
            .six => '^',
            .seven => '&',
            .eight => '*',
            .nine => '(',
            .zero => ')',
            .space => ' ',
            .apostrophe => '"',
            .comma => '<',
            .minus => '_',
            .period => '>',
            .slash => '?',
            .semicolon => ':',
            .equal => '+',
            .left_bracket => '{',
            .backslash => '|',
            .right_bracket => '}',
            .grave_accent => '~',
            else => null,
        };
    }

    return switch (key) {
        .a => 'a',
        .b => 'b',
        .c => 'c',
        .d => 'd',
        .e => 'e',
        .f => 'f',
        .g => 'g',
        .h => 'h',
        .i => 'i',
        .j => 'j',
        .k => 'k',
        .l => 'l',
        .m => 'm',
        .n => 'n',
        .o => 'o',
        .p => 'p',
        .q => 'q',
        .r => 'r',
        .s => 's',
        .t => 't',
        .u => 'u',
        .v => 'v',
        .w => 'w',
        .x => 'x',
        .y => 'y',
        .z => 'z',
        .zero => '0',
        .one => '1',
        .two => '2',
        .three => '3',
        .four => '4',
        .five => '5',
        .six => '6',
        .seven => '7',
        .eight => '8',
        .nine => '9',
        .space => ' ',
        .apostrophe => '\'',
        .comma => ',',
        .minus => '-',
        .period => '.',
        .slash => '/',
        .semicolon => ';',
        .equal => '=',
        .left_bracket => '[',
        .backslash => '\\',
        .right_bracket => ']',
        .grave_accent => '`',
        else => null,
    };
}
